# Generated by Django 4.1.7 on 2023-03-21 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=5, unique=True)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('timezone', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-24), django.core.validators.MaxValueValidator(24)])),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.PositiveIntegerField()),
                ('date_time_departure', models.DateTimeField()),
                ('date_time_arrival', models.DateTimeField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('seats_left', models.PositiveSmallIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('price', models.PositiveSmallIntegerField()),
                ('destination_airport', models.ForeignKey(db_column='destination', on_delete=django.db.models.deletion.RESTRICT, related_name='destination_code', to='flights_app.airport')),
                ('origin_airport', models.ForeignKey(db_column='origin', on_delete=django.db.models.deletion.RESTRICT, related_name='origin_code', to='flights_app.airport')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('outbound_flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flights_app.flight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
